# Generated by Django 5.1.6 on 2025-03-03 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon', models.CharField(default='fas fa-code', help_text="Font Awesome icon class name (e.g., 'fab fa-python')", max_length=50)),
                ('proficiency', models.PositiveIntegerField(default=75, help_text='Proficiency level in percentage (0-100)')),
            ],
        ),
    ]
